[package]
name = "epp_rust"
version = "0.1.0"
authors = ["ShaneEverittM <shane.everitt.murphy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
itertools = "0.10.0"
clap = "2.33.3"